# Generated by Django 4.2.3 on 2023-07-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authblog', '0004_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
